name: Build
on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eranunplugged
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/eranunplugged/up_msg_verification_service:latest -f Dockerfile .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/eranunplugged/up_msg_verification_service
